# Generated by Django 3.1 on 2020-08-22 12:00

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10)),
                ('pub_date', models.DateField(auto_now_add=True)),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=5)),
                ('symptoms', multiselectfield.db.fields.MultiSelectField(choices=[('DC', 'Dry Cough'), ('ST', 'Sore throat'), ('W', 'Weakness'), ('RN', 'Runny nose')], max_length=255)),
                ('additionalInformation', multiselectfield.db.fields.MultiSelectField(choices=[('AP', 'Abdominal pain'), ('V', 'Vomiting'), ('D', 'Diarrhea'), ('CP', 'Chest pain'), ('P', 'pressure'), ('MP', 'Muscle pain'), ('LTS', 'Loss of taste or smell'), ('RS', 'Rash on the skin'), ('DF', 'discoloration of fingers'), ('T', 'toes'), ('LSM', 'Loss of speech movement')], max_length=255)),
                ('score', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
